"""
This type stub file was generated by pyright.
"""

import logging

import typer

logger: logging.Logger
app: typer.Typer

@app.command()
def print_ontology(
    file: str, template: str = ..., skip_disabled: bool = ..., pprint: bool = ...
) -> typer.Exit: ...
