"""
This type stub file was generated by pyright.
"""

import logging
import xml.etree.ElementTree as ET
from collections.abc import Iterable

import typer

from ontovis.types import Group, Path

logger: logging.Logger
app: typer.Typer

def read_document(file: str) -> ET.Element: ...
@app.command()
def print_ontology(
    file: str, template: str = ..., skip_disabled: bool = ..., pprint: bool = ...
) -> typer.Exit: ...
def build_groups(
    paths: Iterable[Path], skip_disabled: bool = ...
) -> dict[str, Group]: ...
