"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterable
from dataclasses import dataclass

@dataclass
class Path:
    enabled: bool
    path_id: str
    is_group: bool
    group_id: str | None
    path_array: list[str]
    ...


@dataclass
class Field:
    name: str
    path: list[str] = ...


@dataclass
class Group:
    name: str
    subgroups: list[Group] = ...
    path: list[str] = ...
    fields: list[Field] = ...
    @classmethod
    def find_group(cls, groups: Iterable[Group], group_id: str) -> Group | None:
        ...
    


